### PR TITLE
Add interactive question which layer to use (fixes #14)

### LINKED ISSUE #14: Different notion of layer
I am a bit confused of the different notion of layer that is of interest and should be used and I have a feeling that this is not to get solved. Yet, I wanted to let you know about my issue, so that we might be able to solve it nonetheless :)

I want to dissect a layer 2 protocol and calculate the FMS. The protocol is the well-known `ethernet` protocol everyone is a fan of. While it *is* a layer 2 protocol, I used the flag `-l 1` in my example, as netzob would try to actually parse this well known protocol that I want to parse with my own tool instead. But even though I already used a lower layer, I needed to hardcode an additional `-1` [here](https://github.com/vs-uulm/nemesys/compare/master...techge:l2pre#diff-3b4e4c4384d55d426ba7479d49867db75d8ea70746b0955326598658f48a3a00R1620) because otherwise FMS would look at the wrong layer. The reason is - as far as I can see - that the notion of *layer* switched from OSI-Model layer to actually dissected protocols here. I saw something like `eth:ethertype:ip:xxx` for `self.protocols`. So the problem at this position of the code is that it is not clear what protocol we are actually looking at. While I do not know how to solve this general problem yet, I thought it might be worth mentioning here for discussion.

I am aware of the fact that this might be the very reason for the `--relativeToIP` flag, but this does not necessarily help here, I am afraid, does it? At least I got my problems to get it right for both notions of layer...

### PR DESCRIPTION
**Pull request by techge**
The layer submitted as a parameter is mostly used in regard of netzobs
importer/the OSI model and does not match the layer count of Wiresharks
dissection. This is why we should ask the user interactively what layer
to use while presenting the layers actually present in the first message.

I can imagine that you will hesitate including this PR, but you may consider it.

We are passing through the `layernumber` and `relativeToIP` parameter a lot, just to do calculations that do not work for some cases (actually for *most of the cases I wanted* to use the comparator). I would prefer this not-perfect-either solution to choose the wireshark dissected layer I want to test instead of fiddling in the code to get what I want...

It looks like this:

```
$ python src/nemesys_fms.py -l 2 input/ethernet/test2.pcapng                                                                                                                                               
Load messages...                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                               
Wait for tshark output (max 20s)...                                                                                                                                                                                                            
[0]: eth                                                                                                                                                                                                                                       
[1]: ethertype                                                                                                                                                                                                                                 
[2]: ip                                                                                                                                                                                                                                        
[3]: udp                                                                                                                                                                                                                                       
[4]: dns                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                               
Which protocol shall we analyze? 0                                                                                                                                                                                                             

Try to remember your decision, but we might need to ask again... 

Segment messages...
[...]
```


Would fix #14

### CODE REVIEW

**Comment by techge** [comment]
PS: The exciting stuff is happening [here](https://github.com/vs-uulm/nemesys/pull/17/files#diff-3b4e4c4384d55d426ba7479d49867db75d8ea70746b0955326598658f48a3a00R1532-R1538).

**Comment by skleber** [comment]
Thank you for this PR. However, I want to retain a mode of operation of the scripts that allow for an unattended batch processing without any interaction.

If you could either change your code in a way that allows to activate this interactive behavior (react to the -i switch for example) I would be inclined to approve this PR.
Ideally, you could change your approach in a way that the protocol name can be used on the command line alternatively to the number, this would be great. However, I do not have a good solution how to map this reliably on Netzob's layered message classes.

**Review by skleber — CHANGES_REQUESTED** [review]
see my comment for the PR

**Comment by skleber** [comment]
This PR has been dormant for some time, the code base has changed considerably, and it cannot be simply merged anymore. I will close the issue and reject the associated PR. If you want to follow up on this, let me know.

**Pull request closed without merging**
