### PR TITLE
Add parseFromPCAP()

### PR DESCRIPTION
**Pull request by techge**
Enables parsing a whole pcap file with tshark instead of parsing raw
packet data in a stream of a tshark process.

This PR should add the functionality without breaking existing code as long there are no positional arguments used. Shall I add the new argument `pcap` to the end instead? I just felt like it is more appropriate at this position in regard of importance...

### CODE REVIEW

**Comment by skleber** [comment]
Could you please add a minimum working example of how you expect to use your modified function call? Pasting it here as comment reply would be great.

**Comment by techge** [comment]
Sure, I am still figuring out how this could work best. The problem is in short that all following parts expect the messages fed in to be similar to the one in the comparator which is not necessarily the case (at least for my approach where I do not use the specimenloader).

The idea is generally to insert the pcap [here](https://github.com/vs-uulm/nemesys/blob/4087944180b55f2e33f474b4785c03755f42a858/src/nemesys_fms.py#L133). While the comparator initialization is working fine so far, using it later on e.g. for the `DissectorMatcher`  is not working.

I more or less just want to feed in a PCAP to the comparator like shown in this PR and comparing the dissection results with netzob symbols I created. I don't know if this message is of any use for you, but I will come back later on :)

**Comment by skleber** [comment]
I don't understand what prevents you from using SpecimenLoader. If you provide me with some code illustrating your approach, I may be able to provide a solution using the SpecimenLoader class or some advice how to work around it in your specific situation.

**Comment by skleber** [comment]
Amendment: Using SpecimenLoader should make your life easier. If it doesn't, I should want to know why. ;)

**Comment by techge** [comment]
I added an example of my take of FMS measurement [here](https://github.com/techge/l2pre/blob/3f630c692b6717ce0a24a7fb6aee0c95d00e97a5/src/l2pre_fms.py#L62). It is not exactly what I would love to see yet, but it already makes use of the mentioned parseFromPCAP() function.

If you think I am doing it all wrong, please let me know :)

The point is just that I am handling pcaps differently for my PRE approach and do not see yet, how I could easily integrate the SpecimenLoader there and especially can not do it these days, because of time constraints.

**Comment by skleber** [comment]
Sorry for the way too long response time on my behalf.

I still want to keep loading of the PCAP separated from the message parsing. So if you could change your PR in a way that the actual PCAP handling is happening in a subclass of BaseLoader this should fulfil this requirement and omit what prevented you from using this class in the first place. And then you should also ideally not need to change the signature of BaseComparator and MessageComparator.

**Review by skleber — CHANGES_REQUESTED** [review]
see my comment for the PR

**Comment by skleber** [comment]
I just pushed a new version that may contain useful code to simplify your task or probably solve the issue altogether:
Please have a look at nemere.validation.tsharkConnector.TsharkOneshot and nemere.validation.messageParser.ParsedMessage.parseOneshot

**Comment by skleber** [comment]
This discussion has been dormant for some time, the code base has changed considerably and the original problem might be solved by this altogether. I will close the issue and reject the associated PR. If you want to follow up on this, let me know.

**Pull request closed without merging**
